- hasura/migrations/1591618615701_alerts/up.sql
- package.json
- scripts/add-alerts.js
- scripts/update-alerts.js
- src/components/alerts/AlertTitle.js
- src/components/alerts/Status.js
- src/components/button/index.js
- src/components/changes/ChangeGroup.js
- src/components/changes/ViewDiff.js
- src/components/changes/index.js
- src/components/collapsible/index.js
- src/components/layout/Nav.js
- src/components/tabs/index.js
- src/models.js
- src/pages/_app.js
- src/pages/alerts/[repo].js
- src/theme.js
- yarn.lock
> feat(alerts): add ui

- targets/frontend/src/components/changes/index.js
- targets/frontend/src/components/dialog/index.js
- targets/frontend/src/components/layout/Nav.js
- targets/frontend/src/components/layout/auth.layout.js
- targets/frontend/src/hoc/CustomUrqlClient.js
- targets/frontend/src/lib/auth/authTokenExchange.js
- targets/frontend/src/lib/auth/token.js
- targets/frontend/src/pages/alerts/[[...params]].js
- targets/frontend/src/pages/alerts/[repo]/[status].js
- fix proptype bugs
- fix navigation issue using hashes(#) in url so I replace them using the new catchall route 
```diff
- /alerts/socialgouv-legidata#todo
+ /alerts/socialgouv-legidata/todo
```
> fix(frontend): reset status when navigate to another alert repo

- targets/frontend/src/components/button/index.js
- targets/frontend/src/components/changes/ViewDiff.js
- targets/frontend/src/components/changes/index.js
- targets/frontend/src/components/pagination/index.js
- targets/frontend/src/hoc/UserProvider.js
- targets/frontend/src/pages/alerts/[[...params]].js
- targets/frontend/src/theme.js
- targets/hasura/migrations/1598542972178_order-view/down.sql
- targets/hasura/migrations/1598542972178_order-view/up.sql
- update diff view
- add pagination
- order v1 view 
- remove div wrapper on button
- remove onChange warning on ViewDiff
> feat(frontend): update diff page

- targets/frontend/src/hoc/UserProvider.js
- targets/frontend/src/hoc/getDisplayName.js
- targets/frontend/src/lib/auth/authTokenExchange.js
- targets/frontend/src/lib/auth/token.js
Making unrelated changes (my bad) on auth in #100 introduce errors + make server side jwt leak around client (well if you was previously connected)
__Major changes__ : 
- attach jwt to ctx on serverside to avoid refreshing jwt token twice (one for withUserProvider, and one un authExchange)
- use inMemoryToken only for client side
> fix:  auth broken :(

- targets/frontend/src/lib/auth/token.js
to avoid sentry log that errors (quite common if trying to access "/" without being authentified before
> fix: don't return a rejected Promise  from getInitialProps 

- targets/frontend/package.json
- targets/frontend/src/pages/api/preview.js
- targets/frontend/src/pages/contenus/[id].js
- yarn.lock
save document and update cdtn-master in ordre to preview future change
> feat(frontend): update change on master

- targets/hasura/metadata/tables.yaml
Update hasura permissions for table kali_blocks
> fix(kali_blocks): update hasura permissions

- targets/alert-cli/src/exportContributionAlerts.js
- targets/frontend/src/components/changes/FicheTravailDataChange.js
- targets/frontend/src/components/changes/ViewDiff.js
Diff is too long (seems like a browser crash) when set to "word" on very long texts
> fix(front): force sentence diff when section is new / removed

- targets/alert-cli/src/__test__/__snapshots__/exportContributionAlerts.test.js.snap
- targets/alert-cli/src/__test__/exportContributionAlerts.test.js
- targets/alert-cli/src/exportContributionAlerts.js
- targets/frontend/src/components/changes/index.js
petit update du format de value 
on envoie un type 
`{type: "added"}` | `{type: "removed"}` | `{type: "modified", etat: {current: string, previous: string} , texts: {current: string, previous: string} }`
poke @ivangabriele
> fix(alert): fix forward alert to contribution api

- .k8s/__tests__/__snapshots__/generate-prod-restore.ts.snap
- .k8s/components/jobs/restore/db.ts
This project pipeline use the legacy `db_SHA` convention instead of `autodevops_SHA` at database creation.
So the restore job was waiting for the wrong database to be ready...
> fix(ci): fix restore job initContainer

- README-dev.md
- README.md
- docker-compose.yml
J'ai ajouté de la documentation pour l'initialisation du projet pour un dev.
J'ai également corrigé, je crois que c'est un petit bug, sur le docker compose pour donner l'adresse de Hasura à l'Ingester.
Il y a deux issues pour des problèmes identifiés mais qui demande réflexion pour les corriger: https://github.com/SocialGouv/cdtn-admin/issues/319 et https://github.com/SocialGouv/cdtn-admin/issues/320
> docs(dev): add documentation for developer

- targets/frontend/src/components/editor/CodeEditor.js
un oubli lors de la derniere PR, l'ordre des import est imoprtant (d'où le commentaire pour désactiver la règle slint)
> fix(frontend): re-orgnaize imports for ace-editor

- targets/alert-cli/.k8s/alert.cronjob.yaml
temporary fix before refactoring alerts (to avoid space issue)
> fix(alert): increase alert storage space

- targets/ingester/src/cli.js
- targets/ingester/src/index.d.ts
- targets/ingester/src/transform/fichesServicePublic/__tests__/parseReferences.test.js
- targets/ingester/src/transform/fichesServicePublic/format.js
- targets/ingester/src/transform/fichesServicePublic/parseReference.js
- handle the new legifrance url
-  every link which does not belong to cdt or kali  is considered an external link ( we re-use the label from the service-public data )  
closes #332
> fix(ingester): handle legifrance new url style

- targets/hasura/migrations/1613478848457_add_audit/down.sql
- targets/hasura/migrations/1613499638772_alert_clean/up.sql
fix latest migration script :/
> fix(hasura): fix migrations

- targets/frontend/src/components/fiches-sp/addFicheForm.js
- targets/frontend/src/components/fiches-sp/fichesSpContainer.js
- targets/frontend/src/components/fiches-sp/list.js
- targets/hasura/metadata/tables.yaml
- targets/hasura/migrations/1616080671217_create_fichesp_view/down.sql
- targets/hasura/migrations/1616080671217_create_fichesp_view/up.sql
- targets/ingester/package.json
- targets/ingester/src/transform/fichesServicePublic/index.js
- mise a jour l'ui de gestion des fiches sp
- création d'une vue dediée
> fix(frontend): update fiches service-public view

- .k8s/__tests__/__snapshots__/generate-prod.ts.snap
- .k8s/environments/prod/alert.configmap.yaml
- targets/alert-cli/src/__test__/exportContributionAlerts.test.js
- targets/alert-cli/src/exportContributionAlerts.js
limit runing exportContributionAlerts to production env
fix #399
> fix(alerts): export contributions alerts only in prod deployement

- .k8s/__tests__/__snapshots__/generate-prod-ingester-elasticsearch.ts.snap
- .k8s/utils/ES_INDEX_PREFIX.ts
I've updated the versionning policy to avoid coupling cdtn release to cdtn-admin release
With the current policy, each time we made a release on cdtn-admin, a new index is created with the version (ex: v1.0.1) in the index name.  the previous index used by cdtn hasn't been updated and if we want to swithc on that index, we will need to made a release / production to retrieve the cdtn-admin version.
using only major version allow us to still update the index, without the need to release / production on cdtn (or only for breaking change)  
what do you think ?
> feat(ingester-es): use only major as elasticsearch index prefix

- .gitlab-ci.yml
- .k8s/components/hasura.ts
Reverts SocialGouv/cdtn-admin#443
in fact, since containers are removed after one day, we could re-use retore data job and run once a day to reset preprod db with the previous day backup
> revert: "feat(gitlab): add manual preprod update"

- shared/elasticsearch/src/dataset/stop_words/stop_words.json
"essai" should not be ignored in our context
> fix(indexation): remove 'essai' from stopwords

- targets/ingester/src/transform/agreements/agreementsWithHighlight.ts
- targets/ingester/src/transform/agreements/index.ts
Avoid overwriting the `highlight` field in the agreements document when new data are available.
co-author @maxgfr
> feat(ingester): keep existing highlight on agreements

- targets/alert-cli/src/diff/dila-data.ts
- targets/frontend/src/components/changes/ChangeGroup.tsx
Correctif rapide sur l'alerting. 
L'alerting n'aime pas quand on a des suppressions/ajouts. Pour le moment, j'ai triché car je bascule entre le previous et le current pour récupérer des informations mais du coup les types ne sont pas bon. Il faut revoir le typescript.
La prochaine étape est d'ajouter des TU pour reproduire les cas et ensuite de refactorer le code pour supporter les différents cas.
fixes #687
> fix(alerting): support agreement removed

- .k8s/__tests__/__snapshots__/generate-dev.ts.snap
- .k8s/__tests__/__snapshots__/generate-preprod.ts.snap
- .k8s/__tests__/__snapshots__/generate-prod.ts.snap
- .k8s/components/alert.cronjob.ts
- .k8s/components/ingester.cronjob.ts
Changement de la valeur de la backoffLimit qui engendrerai la perte de logs quand un cronjob est en échec.
> ci: fix backoffLimit value

- targets/ingester/@types/unist-util-parents.d.ts
- targets/ingester/src/transform/agreements/kaliArticleBytheme.ts
La librairie a changé en version 2.0.0
Le type étant en dur dans notre code, cela ne l'a pas détecté. Il faudrait utiliser les types des libs unist mais je n'ai pas compris grand chose à leurs types...
> fix(ingester): parents is not default exported anymore

- targets/hasura/migrations/1654608190000_trigger_to_updated_at/down.sql
- targets/hasura/migrations/1654608190000_trigger_to_updated_at/up.sql
Il manquait le trigger pour mettre à jour le champ updated_at dans la BDD lorsque l'on édite une donnée.
> fix(contribution): add trigger to update the updated_at field

- targets/frontend/src/pages/api/storage/index.js
- targets/hasura/metadata/databases/default/tables/v1_fiches_travail_data_alerts.yaml
- targets/hasura/metadata/databases/default/tables/v1_fiches_vdd_alerts.yaml
- targets/hasura/metadata/databases/default/tables/v1_kali_data_alerts.yaml
- targets/hasura/metadata/databases/default/tables/v1_legi_data_alerts.yaml
Corrections de deux bugs :
* Problème sur l'upload des fichiers (en fait le premier stream étant lu pour détecté du code malveillant, le code d'azure pour l'upload ne marchait plus). On pense que c'est du à une montée de version de NextJS. Du coup on duplique les streams pour éviter d'altérer le stream d'upload.
* Problème sur les permissions empêchant d'ajouter des fiches sp sur l'admin
> fix(permissions): ajout des permissions sur les tables dans le schéma v1

- .github/workflows/quality.yml
- .github/workflows/release.yml
- .kube-workflow/values.yaml
cf : [github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
> fix(ci): deprecated `set-output` fixed

- targets/frontend/src/components/fiches-sp/fichesSpContainer.js
- targets/frontend/src/components/fiches-sp/list.js
- targets/frontend/src/components/fiches-sp/selectActions.js
- targets/frontend/src/pages/contenus/fiches-sp.tsx
Correctif sur la page fiches-sp de l'admin. 
Il est impossible de supprimer des fiches SP. Lors de la sélection, on concat des tableaux dans des tableaux, ce qui donne la requête GraphQL:
```json
{"query":"mutation deleteServicePublicIds($ids: [String!] = []) {\n  delete_service_public_contents(where: {id: {_in: $ids}}) {\n    affected_rows\n    returning {\n      id\n      __typename\n    }\n    __typename\n  }\n}","operationName":"deleteServicePublicIds","variables":{"ids":[["F35309"]]}}
```
Alors que l'on attend un tableau de string.
J'en ai profité pour ajouter un type sur le context et changé le contenu du context par un objet et non un tableau (plus facile à typer et valider le type avec TS).
> fix(fiches-sp): bug dans la suppression des fiches SP

- targets/frontend/src/lib/emails/activateAccount.ts
- targets/frontend/src/lib/emails/getAccountSecretToken.ts
- targets/frontend/src/pages/api/actions/email_account_activation.ts
- targets/frontend/src/pages/user/new.js
- targets/hasura/metadata/actions.graphql
Voici le correctif :) avec ce nouveau format d'action, on peut également mettre en place un bouton pour renvoyer le mail de validation :)
> fix: ne plus envoyer le secret_token depuis le frontend

- targets/ingester/src/index.d.ts
- targets/ingester/src/lib/hasura-mutations-queries.ts
- targets/ingester/src/transform/agreements/index.ts
Ajout de la partie ingester pour insérer les conventions collectives sans lien legifrance dans la table document.
> feat: gestion des conventions collectives sans page legifrance

- .kontinuous/templates/alert.cronjob.yaml
- .kontinuous/templates/ingester.cronjob.yaml
Changement de l'heure pour le lancer à 3 heure du matin (GMT + 2) afin de suivre le nouvel ordre : https://github.com/SocialGouv/code-du-travail-numerique/wiki#cron-jobs
> feat: mise à jour de l'heure du lancement de l'ingester

- shared/elasticsearch-document-adapter/src/cdtnDocuments.ts
fix #1125
J'ai relancé l'export sur mon PC et ça fonctionne bien 🤩
> fix(contributions): correction des liens vers les conventions collectives 

- .kontinuous/env/prod/values.yaml
On désactive le HPA sur ce service qui n'en a pas besoin. Cela permet de retirer les alertes sur mattermost.
> fix: update replicas for export

- targets/frontend/src/components/forms/EditionField/Editor.tsx
Voici le résultat : 
et sans chatGPT pour le CSS 😄
> fix(contributions): augmentation de la taille des titres des accordéons

- targets/hasura/migrations/default/1702549668954_fix_question_55_index/down.sql
- targets/hasura/migrations/default/1702549668954_fix_question_55_index/up.sql
Sous l'ancien outil de contribution , on a plusieurs index pour la même réponse et lors de la migration, on a choisi le mauvais index :(
> fix(contribution): changement de l'index de la question 54 à 55

- shared/elasticsearch-document-adapter/src/contributions/__tests__/generateMessageBlock.test.ts
- shared/elasticsearch-document-adapter/src/contributions/fetchMessageBlock.ts
- shared/elasticsearch-document-adapter/src/contributions/generateMessageBlock.ts
- targets/frontend/src/components/contributions/questions/EditQuestion.tsx
- targets/frontend/src/components/contributions/questions/EditQuestionForm.tsx
- targets/frontend/src/components/contributions/questions/Question.mutation.ts
- targets/frontend/src/components/contributions/type.ts
- targets/frontend/src/components/forms/EditionField/Editor.tsx
- targets/frontend/src/components/forms/EditionField/MenuSpecial.tsx
- targets/frontend/src/components/forms/EditionField/extensions/Alert.ts
- targets/frontend/src/components/forms/EditionField/extensions/index.ts
On peut maintenant mettre un message block vide à une question et on peut ajouter des blocks d'information (fond bleu) dans les contributions pour rédiger des message block dans le texte.
Linked to https://github.com/SocialGouv/code-du-travail-numerique/issues/5475
> fix(contribution): autoriser un message block vide

- shared/elasticsearch-document-adapter/src/buildThemes.js
fix [#1179](https://github.com/SocialGouv/cdtn-admin/issues/1179)
Pour <https://code.travail.gouv.fr/themes/representation-du-personnel>
> fix(themes): add url for external link

- shared/elasticsearch-document-adapter/src/ingest.ts
Erreur sur la maj des données en prod (2 fois) : 
```
{"level":"error","message":"Failed to index documents ({\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be [474526508/452.5mb], which is larger than the limit of [410412646/391.3mb], real usage: [311706624/297.2mb], new bytes reserved: [162819884/155.2mb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=162819884/155.2mb, model_inference=0/0b, accounting=0/0b]\",\"bytes_wanted\":474526508,\"bytes_limit\":410412646,\"durability\":\"TRANSIENT\"}],\"type\":\"circuit_breaking_exception\",\"reason\":\"[p
arent] Data too large, data for [<http_request>] would be [474526508/452.5mb], which is larger than the limit of [410412646/391.3mb], real …
```
> fix: réduction de la taille du batch de l'export

- shared/types/EditorialContent.ts
- targets/alert-cli/src/diff/dila/extractReferences/editorialContents.ts
> fix(alert-cli): contenus éditoriaux qui peuvent être `undefined` si aucun n'élément est renseigné

- targets/export-elasticsearch/src/ingester/cdtnDocuments.ts
Output
```
01-23 14:09:35.349 | info  | === Contributions === 
01-23 14:09:35.555 | info  | Fetched 1998 contributions 
01-23 14:09:35.587 | info  | Fetched 677 conventions 
01-23 14:09:35.589 | info  | Fetched 1510 old contributions 
01-23 14:09:35.589 | info  | Fetched 488 new contributions 
01-23 14:09:38.533 | info  | Generated 488 new contributions 
01-23 14:09:38.571 | info  | Generated 1510 old contributions 
01-23 14:09:38.572 | info  | › contributions... 1998 items 
01-23 14:09:38.572 | info  | done in 4.426 s
```
> fix(ingester logs): add logs during ingester to debug contributions export

- targets/export-elasticsearch/src/ingester/agreements/getAgreementsArticlesByTheme.ts
- targets/export-elasticsearch/src/ingester/cdtnDocuments.ts
- targets/export-elasticsearch/src/ingester/contributions/fetchFicheSp.ts
- targets/export-elasticsearch/src/ingester/contributions/fetchLinkedContent.ts
- targets/export-elasticsearch/src/ingester/contributions/fetchMessageBlock.ts
- targets/export-elasticsearch/src/ingester/documents/fetchCdtnAdminDocuments.ts
- targets/export-elasticsearch/src/ingester/documents/fetchGlossary.ts
- targets/export-elasticsearch/src/ingester/ingest.ts
- targets/export-elasticsearch/src/ingester/themes/fetchThemes.ts
- targets/export-elasticsearch/src/ingester/types/themes.ts
- targets/export-elasticsearch/src/services/export.ts
Migration de fetch vers urql pour les appels sur la base de données.
Depuis la mise à jour d'hasura, les calls en fetch échouent si on demande trop de données. Comme on utilise urql sur les nouveaux devs de l'export, autant basculer les quelques requêtes en fetch restantes.
Note: J'ai également retiré la fonction génératrice. A voir si ça améliore le debug...
> feat(export): migration de fetch vers urql

- targets/frontend/src/lib/__tests__/secu.test.ts
- targets/frontend/src/lib/secu.ts
- targets/frontend/src/pages/api/storage/index.ts
- targets/frontend/src/pages/fichiers.tsx
> fix(upload): bug sur l'ajout de l'extension

- shared/types/src/elastic/contributions.ts
- shared/types/src/hasura/contributions.ts
- shared/types/src/hasura/editorial-content.ts
- targets/alert-cli/src/diff/dila/extractReferences/__tests__/editorialContents.test.ts
- targets/export-elasticsearch/src/ingester/informations/__tests__/getContentBlockIds.test.ts
Refer to https://github.com/SocialGouv/code-du-travail-numerique/issues/5844
> fix(types): correction des derniers soucis d'harmonisation avec le frontend

- targets/frontend/src/modules/documents/api/documents.service.ts
- targets/frontend/src/modules/models/components/Common/Form.tsx
- targets/frontend/src/modules/models/type.ts
fix: [#1395](https://github.com/SocialGouv/cdtn-admin/issues/1395)
> fix(modele): correction de la création des modèles

- shared/elasticsearch/package.json
- shared/elasticsearch/src/esClientUtils.js
- yarn.lock
Pour corriger le problème sur l'installation du package via une lib externe
> fix(cdtn-elasticsearch): use `console` instead of `logger`

- .kontinuous/env/prod/values.yaml
Adjust cdt-admin resources www, hasura, cnpg
> fix: cdtn-admin update resources

- shared/types/package.json
- shared/types/src/elastic/agreements.ts
- shared/types/src/elastic/code-du-travail.ts
- shared/types/src/elastic/common.ts
- shared/types/src/elastic/contributions.ts
- shared/types/src/elastic/editorial-content.ts
- shared/types/src/elastic/fiche-travail.ts
- shared/types/src/elastic/highlights.ts
- shared/types/src/elastic/modeles-de-courrier.ts
- shared/types/src/elastic/prequalified.ts
- shared/types/src/elastic/theme.ts
- shared/types/src/elastic/tools.ts
- shared/types/src/hasura/agreement.ts
- shared/types/src/hasura/code-du-travail.ts
- shared/types/src/hasura/common.ts
- shared/types/src/hasura/editorial-content.ts
- shared/types/src/hasura/fiche-sp.ts
- shared/types/src/hasura/fiche-travail.ts
- shared/types/src/hasura/highlights.ts
- shared/types/src/hasura/modeles-de-courrier.ts
- targets/alert-cli/src/diff/dila/extractReferences/__tests__/ficheTravailEmploi.test.ts
- targets/export-elasticsearch/src/ingester/cdtnDocuments.ts
- yarn.lock
Linked to https://github.com/SocialGouv/code-du-travail-numerique/issues/6196
> fix(types): utilisation de `cdtn-utils` au lieu de `cdtn-source` qui n'est plus d'actualité

- targets/ingester/src/transform/fiche-travail-emploi.ts
closes [#1496](https://github.com/SocialGouv/cdtn-admin/issues/1496)
> feat: disable glossary on fiches MT

- targets/alert-cli/src/diff/sp/getContributionsWithFicheSp.ts
- targets/frontend/src/components/contributions/answers/answer.query.ts
- targets/frontend/src/modules/contribution/api/query.ts
- targets/hasura/metadata/databases/default/tables/contribution_answers.yaml
> fix(contributions): correction des contributions avec une fiche SP

- shared/types/src/elastic/fiche-service-public.ts
- targets/ingester/src/transform/fichesServicePublic/__tests__/ficheSP-mock.json
- targets/ingester/src/transform/fichesServicePublic/__tests__/format.test.ts
- targets/ingester/src/transform/fichesServicePublic/__tests__/formatted-raw-ficheSP.json
- targets/ingester/src/transform/fichesServicePublic/__tests__/parseReferences.test.ts
- targets/ingester/src/transform/fichesServicePublic/format.ts
https://github.com/SocialGouv/code-du-travail-numerique/issues/6232#issuecomment-2498419733
> fix(fiche SP): ne plus afficher en bas de page les liens "Voir aussi", "Pour en savoir plus" et "Service en ligne"

- targets/export-elasticsearch/src/workers/glossary/__mocks__/glossaryData.ts
- targets/export-elasticsearch/src/workers/glossary/__tests__/addGlossaryContent.test.ts
- targets/export-elasticsearch/src/workers/glossary/explodeGlossaryTerms.ts
> fix(glossary): correction des `&nbsp;` sur la reconnaissance des mots

- targets/frontend/src/components/documents/Container.js
- targets/frontend/src/components/documents/List.js
Par contre, la recherche n'est pas optimale et ça devient compliqué de l'optimiser car l'idcc et le numéro de la question sont dans le document qui est un json.
> feat(contribution): ajout des contributions conventionnelles dans la liste des documents

- targets/frontend/src/modules/contribution/mapContributionToDocument.ts
Petit fix pour corriger l'affichage de la question dans l'administration. On met à jour le titre avec la question à chaque fois car on peut désormais modifier le titre de la question.
> fix: mise à jour du title de la contribution à la publication
