targets/www/.gitlab-ci.yml, targets/www/.k8s/environments/dev/www-env.configmap.yaml, targets/www/.k8s/environments/prod/www-env.configmap.yaml, targets/www/.k8s/www.values.yml
=> build(k8s): add env configmap

targets/alert/.gitlab-ci.yml
=> ci(alert): add manual cron trigger

targets/frontend/.env, targets/frontend/src/components/Roles.js, targets/frontend/src/components/layout/Nav.js, targets/frontend/src/components/user/List.js, targets/frontend/src/hoc/CustomUrqlClient.js, targets/frontend/src/lib/auth/authTokenExchange.js, targets/frontend/src/pages/alerts/[repo].js, targets/frontend/src/pages/api/login.js, targets/frontend/src/pages/user/new.js
fix urql client HOC due to a breaking change
=> fix(front): fix urql latest version breaking change

targets/hasura/migrations/1595231600880_alerts_uniq/down.sql, targets/hasura/migrations/1595231600880_alerts_uniq/up.sql
i've ran into problem when restarting hasura, so I fix it
=> fix(hasura): remove constraint if exists in alert constraint migration

targets/alert-cli/src/index.js
matched pattern based on id only was to loose
=> fix(alerts): use an accurate regexp for fiche-sp filter

Dockerfile, targets/alert-cli/Dockerfile, targets/frontend/Dockerfile
this fix the rehydration wraning due to date between server / client
=> chore(docker): node 14

targets/alert-cli/src/batchPromises.js, targets/alert-cli/src/index.js
=> fix(alerts): batch alert insert

package-scripts.yml, shared/graphql-client/package.json, targets/alert-cli/package.json, targets/alert-cli/src/index.js, targets/frontend/package.json, targets/frontend/src/components/Roles.js, targets/frontend/src/components/alerts/AlertTitle.js, targets/frontend/src/components/alerts/Status.js, targets/frontend/src/components/button/index.js, targets/frontend/src/components/comments/Comment.js, targets/frontend/src/components/comments/CommentForm.js, targets/frontend/src/components/comments/CommentList.js, targets/frontend/src/components/comments/index.js, targets/frontend/src/components/layout/Nav.js, targets/frontend/src/components/layout/auth.layout.js, targets/frontend/src/components/list/index.js, targets/frontend/src/components/tabs/index.js, targets/frontend/src/pages/alerts/[[...params]].js, targets/frontend/src/pages/users.js, targets/frontend/src/theme.js, targets/hasura/metadata/tables.yaml, targets/hasura/migrations/1597155113177_create_table_public_alert_notes/down.sql, targets/hasura/migrations/1597155113177_create_table_public_alert_notes/up.sql, targets/hasura/migrations/1597337373820_source_label/down.sql, targets/hasura/migrations/1597337373820_source_label/up.sql, yarn.lock
=> Add alert note

targets/frontend/src/components/button/index.js, targets/frontend/src/components/changes/ChangeGroup.js, targets/frontend/src/components/changes/index.js, targets/frontend/src/components/collapsible/index.js, targets/frontend/src/components/layout/auth.layout.js, targets/frontend/src/components/list/index.js, targets/frontend/src/theme.js
- fix missing diff text button
- small ui update on Changes / Diff
=> fix(frontend): add text diff view

targets/frontend/src/components/alerts/AlertTitle.js, targets/frontend/src/components/button/index.js, targets/frontend/src/components/changes/index.js, targets/frontend/src/pages/alerts/[[...params]].js
- add a link to ccn
- fix section links display 
- use beta.legifrance as base url
=> fix(frontend): update link to beta.legifrance.gouv

targets/frontend/src/components/comments/index.js, targets/frontend/src/components/layout/Nav.js, targets/frontend/src/components/pagination/index.js, targets/frontend/src/hoc/UserProvider.js, targets/frontend/src/hooks/useUser.js, targets/frontend/src/lib/auth/jwt.js, targets/frontend/src/lib/auth/token.js, targets/frontend/src/pages/alerts/[[...params]].js, targets/frontend/src/pages/api/login.gql.js, targets/frontend/src/pages/api/login.js, targets/frontend/src/pages/api/refreshToken.gql.js, targets/frontend/src/pages/api/refresh_token.js, targets/frontend/src/pages/user/edit/[id].js, targets/frontend/src/theme.js
avoid re-render due to useUSer based on useEffect 
closes #53
=> refactor(frontend): simplify useUser hook to read info from jwt

targets/hasura/migrations/1591618615701_alerts/down.sql
=> fix(hasura): remove truncate in down.sql

targets/alert-cli/src/diff/fiches-travail-data.js, targets/alert-cli/src/diff/fiches-vdd.js, targets/alert-cli/src/index.d.ts, targets/alert-cli/src/index.js, targets/alert-cli/src/node-git.helpers.js, targets/frontend/src/components/changes/FicheTravailDataChange.js, targets/frontend/src/components/changes/index.js
=> feat(alert): add travail-emploi alert

targets/frontend/.k8s/environments/dev/www-env.configmap.yaml, targets/frontend/.k8s/environments/prod/www-env.configmap.yaml, targets/frontend/src/pages/_app.js
=> feat(frontend): add sentry release info

targets/alert-cli/src/diff/fiches-travail-data.js, targets/alert-cli/src/diff/fiches-vdd.js, targets/alert-cli/src/index.d.ts, targets/alert-cli/src/relevantContent.js
handle sections change (added / removed / updated)
=> fix(alert): handle new section

targets/hasura/metadata/tables.yaml
allow anonymous role to fetch documents
=> fix(hasura): allow anonymous get on documents

targets/hasura/migrations/1600080497002_documents/up.sql
=> fix(hasura): fix procedure name for updated_at trigger

targets/ingester/@types/fiches-vdd.d.ts, targets/ingester/src/cli.js, targets/ingester/src/transform/fichesServicePublic/filter.js, targets/ingester/src/transform/fichesServicePublic/format.js, targets/ingester/src/transform/fichesServicePublic/index.js
use cdtn filtering for fiche-vdd
=> fix(ingester): use cdtn filtering for fiche vdd

targets/hasura/migrations/1604939228600_alter_table_public_documents_add_column_is_available/down.sql, targets/hasura/migrations/1604939228600_alter_table_public_documents_add_column_is_available/up.sql, targets/ingester/src/cli.js, targets/ingester/src/lib/batchPromises.js, targets/ingester/src/transform/agreements.js, targets/ingester/src/transform/code-du-travail.js
- use cid to generate cdtn_id
- group documents insert (chunk of 100 documents)
- add a new property is_available to identify obsolete documents
=> fix(ingester): use cid to generate cdtn_id

targets/alert-cli/src/index.js, targets/hasura/.k8s/hasura.values.yml, targets/ingester/src/cli.js
- ingester will exit on error
- batch update availability by source rather than in one run
=> fix(ingester): exit on error

targets/frontend/src/components/changes/index.js
=> fix: fix professionel-entreprise link

.env, targets/frontend/src/components/button/index.js, targets/frontend/src/components/glossary/TermList.js, targets/frontend/src/components/layout/Inline.js, targets/frontend/src/components/layout/Nav.js, targets/frontend/src/components/pagination/index.js, targets/frontend/src/components/themes/Form.js, targets/frontend/src/components/themes/List.js, targets/frontend/src/pages/alerts/[[...params]].js, targets/frontend/src/pages/api/elasticcloud/preview.js, targets/frontend/src/pages/api/webhooks/publication.js, targets/frontend/src/pages/contenus/[id].js, targets/frontend/src/pages/contenus/index.js, targets/frontend/src/pages/themes/[[...id]].js, targets/hasura/.gitlab-ci.yml, targets/hasura/.k8s/hasura.values.yml, targets/hasura/metadata/tables.yaml
=> feat(frontend): publish document

targets/frontend/src/components/forms/Lister/index.js, targets/frontend/src/components/glossary/TermForm.js, targets/frontend/src/pages/glossary/edit/[[...id]].js, targets/frontend/src/pages/glossary/index.js, targets/hasura/metadata/tables.yaml, targets/hasura/migrations/1606230745147_new_glossary/down.sql, targets/hasura/migrations/1606230745147_new_glossary/up.sql
closes https://github.com/SocialGouv/code-du-travail-numerique/issues/3157
=> feat(data): add slug to glossary entries

targets/hasura/Dockerfile, targets/hasura/config.yaml, targets/hasura/metadata/tables.yaml, targets/hasura/migrations/1606401836569_version/down.sql, targets/hasura/migrations/1606401836569_version/up.sql, targets/ingester/src/cli.js
add a document_version table to save ingested document version (so we could later used it in cdtn)
closes #171
=> feat(ingester): save ingested document version

targets/frontend/src/lib/preview/glossary.js, targets/frontend/src/pages/api/elasticcloud/preview.js
=> refactor(frontend): update glossary format

targets/frontend/src/pages/contenus/[id].js
=> feat(frontend): add text to editable fields

targets/frontend/src/pages/contenus/[id].js, targets/frontend/src/pages/contenus/index.js
j'ai fait un test pour réparer et simplifier la gestion des filtre /pagination via l'url 
\cc @UnbearableBear qu'est ce que t'en pense ?
=> fix(frontend): fix pagination url

targets/alert-cli/src/__test__/__snapshots__/exportContributionAlerts.test.js.snap, targets/alert-cli/src/__test__/exportContributionAlerts.test.js, targets/alert-cli/src/exportContributionAlerts.js
=> tests: add exportContributionAlerts snapshot

targets/frontend/.gitlab-ci.yml, targets/frontend/.k8s/www.values.yml
This restrict access to prod environment by IP
=> fix: restrict frontend ingress to some IPs

targets/frontend/src/components/alerts/AlertTabs.js, targets/frontend/src/components/layout/Nav.js, targets/frontend/src/components/pagination/index.js, targets/frontend/src/models.js, targets/frontend/src/pages/alerts/[[...params]].js, targets/frontend/src/pages/contenus/index.js
I've broke  alert pagination with last pagination update :/
=> fix(frontend): fix pagination on alert

targets/frontend/Dockerfile
try to fix frontend docker image
=> fix(frontend): copy shared into image

targets/ingester/package.json, targets/ingester/src/index.d.ts, targets/ingester/src/transform/agreements.js, yarn.lock
check https://github.com/SocialGouv/code-du-travail-numerique/issues/3063
needs https://github.com/SocialGouv/kali-data/pull/145 first
=> feat(ccns): add synonyms to conventions collectives

targets/frontend/src/pages/api/actions/preview.js, targets/frontend/src/pages/contenus/edit/[id].js, targets/hasura/metadata/actions.graphql
fix action and flatten param shape
=> fix: preview on preprod

targets/frontend/src/components/layout/Nav.js
=> fix(frontend): re-add files item in nav

targets/alert-cli/src/index.js, targets/ingester/src/cli.js
=> fix(alerts): exit(1) on fail

targets/frontend/package.json, targets/frontend/src/pages/api/sitemap.js, yarn.lock
this pr add a new api endpoint that output a base sitemap to use in cdtn
```xml
<urlset>
<url>
<loc>host.domain/</loc>
<lastmod>2021-01-07T13:33:05.136Z</lastmod>
<priority>0.8</priority>
</url>
<url>
<loc>host.domain/code-du-travail/r4534-121</loc>
<lastmod>2021-01-07T13:32:24.167809+00:00</lastmod>
<priority>0.5</priority>
</url>
</urlset>
```
=> feat(frontend): generate a base sitemap

targets/alert-cli/.k8s/alert.cronjob.yaml
temporary fix before finding a better solution
=> fix(alerts): increase storage to 8gi

targets/alert-cli/src/diff/fiches-travail-data.js, targets/frontend/src/components/changes/FicheTravailDataChange.js, targets/hasura/migrations/1610533021186_migrate-sources-tag/down.sql, targets/hasura/migrations/1610533021186_migrate-sources-tag/up.sql
fix #265 wich lead to a problem when detecting modified documents
=> fix(alerts): fix corrupted data

targets/frontend/src/pages/api/sitemap.js
add glossary and fixe pagination -___-!  
thx @revolunet
=> fix(frontend): update sitemap endpoint

targets/frontend/src/components/editorialContent/ContentSections/MarkdownPreviewModal.js, targets/frontend/src/components/editorialContent/Form.js, targets/frontend/src/components/forms/ContentPicker/ContentSearch.js, targets/frontend/src/components/forms/ContentPicker/index.js, targets/frontend/src/components/highlights/Form.js, targets/frontend/src/components/layout/Nav.js, targets/frontend/src/lib/relations.js, targets/frontend/src/pages/contenus/create/[[...source]].js, targets/frontend/src/pages/contenus/edit/[id].js, targets/frontend/src/pages/contenus/index.js, targets/ingester/src/transform/contributions.js
=> feat: add highlights

shared/types/index.d.ts, targets/alert-cli/src/extractDilaReferences/contribution.js, targets/alert-cli/src/index.js
handle splitted contributions ^__^'
=> fix(alert): handle splitted contribution

targets/frontend/.k8s/www.values.yml, targets/frontend/src/pages/api/webhooks/account.js
use CI_ENVIRONMENT_URL for use in mail
=> fix(frontend): use ci_environment_url for mail

.gitlab-ci.yml, .releaserc.yml
=> ci(gitlab): activate releases

.gitlab-ci.yml, .releaserc.yml, lerna.json, shared/graphql-client/package.json, shared/id-generator/package.json, shared/types/package.json, targets/alert-cli/package.json, targets/frontend/package.json, targets/ingester/package.json
=> Release 1.0.0

.k8s/components/jobs/restore/db.ts
Sorry, the password was also using a new format
=> fix(restore): fix for legacy db password

targets/alert-cli/src/__test__/exportContributionAlerts.test.js, targets/alert-cli/src/exportContributionAlerts.js, targets/alert-cli/src/index.js
add some log around sending alerts to contrib
=> fix(alert): add console arount sending contributions

.gitlab-ci.yml
for clarity, it restores container and database
=> chore: rename restore job

targets/ingester/src/cli.js
=> fix(ingester): update package data even if not present in the database

README-dev.md, targets/hasura/migrations/1613499638772_alert_clean/down.sql, targets/hasura/migrations/1613499638772_alert_clean/up.sql
- remove alerts older than 3 monthes
closes #302
=> feat(hasura): remove old alerts

targets/frontend/src/pages/contenus/index.js
=> fix(frontend): remove cdt and dulpicate contribution from /contenus

targets/frontend/src/pages/alerts/[[...params]].js
=> feat(alert): add a tooltip to show the CCN title

.gitlab-ci.yml, .k8s/__tests__/__snapshots__/generate-prod-restore.ts.snap, .k8s/package.json, .k8s/yarn.lock
Reverts SocialGouv/cdtn-admin#349
=> Revert "fix(deps): update all dependencies (patch)"

targets/frontend/src/components/login/index.js, targets/frontend/src/hoc/CustomUrqlClient.js, targets/frontend/src/hoc/UserProvider.js, targets/frontend/src/lib/auth/jwt.js, targets/frontend/src/lib/auth/token.js
small pr to avoid calling refresh token to often (from both client / server). also add some logging to better track what happen since plataform has problem :/
=> feat(frontend): fix multiple auth

targets/ingester/src/cli.js, targets/ingester/src/index.d.ts, targets/ingester/src/transform/agreements/getKaliBlock.js, targets/ingester/src/transform/agreements/index.js, targets/ingester/src/transform/agreements/kaliArticleBytheme.js
use kaliblock from admin rather than deprecated datafiller
=> fix(ingester): use kaliblock from admin

.gitlab-ci.yml, infra/logger/.eslintignore, infra/logger/.eslintrc.yml, infra/logger/.gitignore, infra/logger/.gitlab-ci.yml, infra/logger/package.json, infra/logger/src/index.test.ts, infra/logger/src/index.ts, infra/logger/tsconfig.build.json, infra/logger/tsconfig.json, lerna.json, package.json, yarn.lock
=> feat(infra): logger module

elasticsearch.md
explain on how we shoudl handle api token
for now we use user / role management but I propose to migrate to api key token
=> docs: add elastic management role

.k8s/__tests__/__snapshots__/generate-dev-restore.ts.snap, .k8s/__tests__/__snapshots__/generate-preprod-restore.ts.snap, .k8s/__tests__/generate-preprod-restore.ts, .k8s/components/jobs/restore/db.ts, .k8s/components/jobs/restore/post-restore.sql, .k8s/utils/PG_ENVIRONMENT_SLUG.ts
=> build(k8s): make the restore db use preprod db on preprod

.gitlab-ci.yml
=> ci(gitlab): remove kapp from stop env

targets/alert-cli/src/diff/dila.js, targets/alert-cli/src/diff/fiches-travail-data.js, targets/alert-cli/src/diff/fiches-vdd.js, targets/alert-cli/src/index.js
use git patch metadata  (removed / added / modified) to avoid doingdiff
on removed files
fix #404
=> fix(alerts): handle fiches-vdd remove old files

docker-compose.yml, targets/frontend/next.config.js, targets/frontend/src/components/button/GitlabButton.js, targets/frontend/src/lib/gitlab.api.js, targets/frontend/src/pages/api/actions/pipelines.js
handle new TRIGGER pipeline var
=> fix: update trigger button

.k8s/__tests__/__snapshots__/generate-prod-sitemap-uploader.ts.snap, .k8s/environments/prod/sitemap-uploader/preprod.configmap.yaml, .k8s/environments/prod/sitemap-uploader/prod.configmap.yaml
=> fix(k8s): update sitemap updloader api url

.k8s/__tests__/__snapshots__/generate-dev-sitemap-uploader.ts.snap, .k8s/__tests__/__snapshots__/generate-prod-sitemap-uploader.ts.snap, .k8s/components/jobs/sitemap-uploader/index.ts, targets/frontend/src/pages/api/sitemap.js
remove sedin sitemap url and let the api  deal with it
=> fix(k8s): let sitemap script handle baseurl

.k8s/__tests__/__snapshots__/generate-prod-sitemap-uploader.ts.snap, .k8s/components/jobs/sitemap-uploader/index.ts, .k8s/environments/dev/sitemap-uploader/index.ts
invert process.env.BASE_URL and env.BASE_URL to passe BASE_URL to sitemap uploader
=> fix(k8s): use env.BASE_URL and fallback on proces.env.BASE_URL

shared/elasticsearch-document-adapter/package.json, shared/elasticsearch-document-adapter/src/cdtnDocuments.js, shared/elasticsearch-document-adapter/src/ingest.js, shared/elasticsearch/src/vectorizer/index.js, targets/ingester-elasticsearch/package.json
fix got call (request shoud use post over get) 
increase retry  count and remove p-retry
=> fix(ingester-es): replace p-retry with got internal retry

targets/frontend/src/lib/auth/token.js
try to fix error send to sentry (#419)
=> fix(frontend): check before send header when redirect to login

.k8s/__tests__/__snapshots__/generate-dev-ingester-elasticsearch.ts.snap, .k8s/utils/ES_INDEX_PREFIX.ts
add version in branch index name
=> fix(ingester-es): add version on branch index name

targets/frontend/src/components/editorialContent/ContentSections/Section.js, targets/frontend/src/components/editorialContent/ReferenceBlocks/References.js, targets/frontend/src/components/editorialContent/ReferenceBlocks/index.js, targets/frontend/src/components/forms/ContentPicker/ThemePicker.js, targets/frontend/src/components/forms/ContentPicker/index.js, targets/frontend/src/components/forms/IconPicker.js, targets/frontend/src/components/forms/Lister/index.js, targets/frontend/src/components/highlights/Form.js
fix react-hook-form api changes (controller and register) 
- fix highlight documents  not shown
- error 500 in glossary and information
- theme icons
- theme selection
=> fix(frontend): upgrade missing react-hook-form register

.gitlab-ci.yml, .k8s/__tests__/__snapshots__/generate-dev.ts.snap, .k8s/__tests__/__snapshots__/generate-preprod.ts.snap, .k8s/__tests__/__snapshots__/generate-prod.ts.snap, .k8s/__tests__/generate-dev-ingester-elasticsearch.ts, .k8s/__tests__/generate-dev-restore.ts, .k8s/__tests__/generate-dev-sitemap-uploader.ts, .k8s/__tests__/generate-dev.ts, .k8s/__tests__/generate-preprod-restore.ts, .k8s/__tests__/generate-preprod.ts, .k8s/__tests__/generate-prod-cleanup-db.ts, .k8s/__tests__/generate-prod-ingester-elasticsearch.ts, .k8s/__tests__/generate-prod-sitemap-uploader.ts, .k8s/__tests__/generate-prod.ts, .k8s/components/alert.cronjob.ts, .k8s/components/hasura.ts, .k8s/components/ingester.cronjob.ts, .k8s/components/www.ts, targets/alert-cli/.gitlab-ci.yml, targets/frontend/.gitlab-ci.yml, targets/frontend/Dockerfile, targets/hasura/.gitlab-ci.yml, targets/ingester-elasticsearch/.gitlab-ci.yml, targets/ingester/.gitlab-ci.yml
same as https://github.com/SocialGouv/code-du-travail-numerique/pull/3461
NB : both projects publish images into the same `HARBOR_PROJECT` (cdtn)
So we need to be careful with the images names (`cdtn-admin-hasura` vs `hasura`)
=> feat(ci): use kaniko + harbor

.k8s/__tests__/__snapshots__/generate-prod-cleanup-db.ts.snap, .k8s/components/jobs/cleanup-db/cleanup.sql, .k8s/components/jobs/ingester-elasticsearch/index.ts
=> fix(hasura): fix cleanup db sql

.husky/pre-commit, package.json, targets/frontend/package.json, targets/ingester/package.json
=> chore(husky): unify precommit script

.husky/pre-push, .k8s/package.json, shared/elasticsearch-document-adapter/package.json, shared/elasticsearch/package.json, shared/logger/package.json, targets/frontend/package.json, targets/ingester-elasticsearch/package.json, targets/ingester/package.json, yarn.lock
=> chore(husky): unify prepush script

.husky/pre-push
=> chore(husky): diff with master .k8s files on prepush

shared/elasticsearch-document-adapter/.gitignore, shared/elasticsearch-document-adapter/package.json, shared/elasticsearch/.gitignore, shared/elasticsearch/package.json, shared/logger/.gitignore, shared/logger/package.json, targets/frontend/.gitignore, targets/frontend/package.json, targets/ingester-elasticsearch/.gitignore, targets/ingester-elasticsearch/package.json, targets/ingester/.gitignore, targets/ingester/package.json
=> chore(husky): add eslint cache on precommit

.gitlab-ci.yml, .k8s/__tests__/__snapshots__/generate-dev-restore.ts.snap, .k8s/__tests__/__snapshots__/generate-dev.ts.snap, .k8s/__tests__/__snapshots__/generate-preprod-restore.ts.snap, .k8s/__tests__/__snapshots__/generate-preprod.ts.snap, .k8s/__tests__/__snapshots__/generate-prod.ts.snap, .k8s/components/jobs/restore/post-restore.sql, .k8s/package.json, .k8s/yarn.lock
replace https://github.com/SocialGouv/cdtn-admin/pull/459
=> fix(ci): update ci deps

targets/frontend/src/components/editorialContent/ReferenceBlocks/index.js
=> fix(frontend): fix typo on references radio name

shared/types/index.d.ts, targets/alert-cli/src/diff/dila-data.ts, targets/alert-cli/src/index.ts, targets/hasura/migrations/1622826255588_fix_may_migration/down.sql, targets/hasura/migrations/1622826255588_fix_may_migration/up.sql, targets/ingester/src/cli.ts
- update AlertInfo format to avoid duplicating alerts 
- add a migration to update info data format and remove duplicate alerts
close #468
=> fix(alerts): avoid  duplicating alerts 

targets/ingester/package.json, targets/ingester/src/transform/agreements/kaliArticleBytheme.ts
=> fix(ingester): pass a node to find for kaliblock

shared/types/index.d.ts, targets/alert-cli/src/__tests__/relevantContent.test.ts, targets/alert-cli/src/diff/dila-data.ts, targets/alert-cli/src/diff/dila-relevantContent.ts, targets/alert-cli/src/diff/fiches-travail-data.ts, targets/alert-cli/src/diff/fiches-vdd.ts, targets/alert-cli/src/diff/preQualified-relevantContent.ts, targets/alert-cli/src/extractDilaReferences/contribution.ts, targets/alert-cli/src/extractDilaReferences/ficheTravailEmploi.ts, targets/alert-cli/src/extractDilaReferences/getAllDocumentsBySource.ts, targets/alert-cli/src/extractDilaReferences/getDocumentQuery.gql.ts, targets/frontend/src/components/changes/ChangeGroup.tsx, targets/frontend/src/pages/alerts/[[...params]].tsx, targets/hasura/migrations/1623671351346_add_prequalified_alert/down.sql, targets/hasura/migrations/1623671351346_add_prequalified_alert/up.sql
add prequalidied to documents
closes #444
=> feat(alert): add prequalified

.k8s/package.json, .k8s/yarn.lock
=> chore(lock): update k8s lock file

targets/frontend/src/components/editorialContent/Form.js
=> fix(frontend): fix references in editorial content

.k8s/__tests__/__snapshots__/generate-preprod.ts.snap, .k8s/__tests__/__snapshots__/generate-prod.ts.snap, .k8s/components/www.ts
=> fix(k8s): rm hpa

targets/ingester/src/transform/fichesServicePublic/parseReference.ts
=> fix(ingester): fix fiches-vdd references label

.gitlab-ci.yml
=> fix(ci): fix on_stop

.k8s/__tests__/__snapshots__/generate-dev-restore.ts.snap, .k8s/__tests__/__snapshots__/generate-preprod-restore.ts.snap, .k8s/package.json, .k8s/yarn.lock
=> chore(deps): @socialgouv/kosko-charts update 6.4.2

shared/elasticsearch/src/esClientUtils.js
Pour le moment, je ne reproduis pas le soucis en local avec un batch à plus de 1000. L'idée est de voir si on reproduit sur le CI avec un plus gros batch. J'ai également apporté un fix pour voir si ça aide.
=> fix(ingester): Exit the process when an error occurs while filling es

shared/elasticsearch-document-adapter/src/fichesTravailSplitter.js
Fiches MT are back to search results !
=> fix(ingestion): set excludeFromSearch in split fiches MT

targets/alert-cli/.gitlab-ci.yml, targets/ingester-elasticsearch/.gitlab-ci.yml, targets/ingester/.gitlab-ci.yml
=> ci(ingester): ensure to fail if not completed

targets/frontend/next-env.d.ts, targets/frontend/src/components/documents/SearchFilters.js, targets/frontend/src/components/layout/Nav.js
also fix a minor ui bug on active link
fix #524
=> fix(frontend): fix source selection in document list

shared/elasticsearch-document-adapter/src/ingest.js
=> fix(ingester-es): fail on vectorization error

targets/alert-cli/src/diff/dila-data.ts, targets/alert-cli/src/diff/fiches-travail-data.ts, targets/alert-cli/src/diff/fiches-vdd.ts, targets/alert-cli/src/index.ts, targets/alert-cli/src/types.ts
move the fileFilter call inside the getDiff function to handle edge case for fiche sp .
This allow to have a difference strategy pour added file vs removed / modifed patch
fix #487
=> fix(alert): improve added alert for service-public

targets/ingester-elasticsearch/README.md, targets/ingester-elasticsearch/scripts/create-keys.sh
Add sample script to create initial API tokens on some cluster
=> chore(ingester): add create keys script

shared/elasticsearch/src/vectorizer/index.js
allow got to retry on POST 
https://github.com/sindresorhus/got/blob/main/documentation/7-retry.md#methods
=> fix(elastic): fix vectorizer retry

.gitlab-ci.yml, .k8s/__tests__/__snapshots__/generate-dev-restore.ts.snap, .k8s/__tests__/__snapshots__/generate-preprod-restore.ts.snap, .k8s/components/jobs/restore/container.ts
make RestoreContainer task more dynamic depending on the context (review branch, preprod, prod)
=> fix(ci): use var for  file container copy

.gitlab-ci.yml, .k8s/components/jobs/restore/container.ts
- fix restore container preprod
- add restore container on triggered pipeline
=> fix(k8s): update preprod restore 

shared/elasticsearch-document-adapter/src/ingest.js
- remove onIdle queue 
- add log when promise of all jobs resolved
- set document number to 1000 forbulk ingest
=> fix(ingester-es): remove onIdle

.gitlab-ci.yml
override PROJECT_PATH wich override CI_PROJECT_PATH
this should help with release / notify job
=> fix: use project_path

.k8s/__tests__/__snapshots__/generate-dev-restore.ts.snap, .k8s/__tests__/__snapshots__/generate-preprod-restore.ts.snap, .k8s/__tests__/__snapshots__/generate-prod-restore.ts.snap, .k8s/components/jobs/restore/container.ts, .k8s/components/jobs/restore/db.ts
this makes it possible to restart the job
=> fix(ci): use unique job names for restore jobs

.gitlab-ci.yml
=> fix(gitlab): use kapp to apply the restore container job

.gitlab-ci.yml
remove allow failure so job will be marked as failed in admin dashbord
=> fix(ci): remove allow failure for triggered update job

targets/alert-cli/src/diff/preQualified-relevantContent.ts, targets/alert-cli/src/extractDilaReferences/contribution.ts, targets/alert-cli/src/extractDilaReferences/ficheTravailEmploi.ts, targets/alert-cli/src/extractDilaReferences/getAllDocumentsBySource.ts, targets/alert-cli/src/extractDilaReferences/getDocumentQuery.gql.ts
add theme in service-public  / travail-emploi alerts
#492
=> feat(alerts): add relalated theme for doc alerts

targets/frontend/src/components/storage/DropZone.js, targets/frontend/src/pages/fichiers.js
=> fix(frontend): support svg in upload

shared/types/index.d.ts, targets/alert-cli/src/extractDilaReferences/__tests__/editorialContents.test.ts, targets/alert-cli/src/extractDilaReferences/__tests__/mocks/editorialContent.payload.json, targets/alert-cli/src/extractDilaReferences/editorialContent.ts
track references for EditorialContent pages
=> feat(alert): handle alert for information pages

README-dev.md
ajout des dépots git liés au code du travail
=> doc: add linked repositories

targets/frontend/src/lib/azure.js
=> fix(frontend): add mimetype to updloaded document on azure

targets/frontend/src/components/documents/List.js, targets/frontend/src/components/home/DuplicateItems.tsx, targets/frontend/src/components/home/InvisibleLinkedDocument.tsx, targets/frontend/src/components/home/UnThemedContent.js, targets/frontend/src/pages/ghost-documents.tsx, targets/frontend/src/pages/index.js
- ajout de la tuile sur la home
- ajout d'une page qui liste les document à  corriger
closes #624
=> feat(frontend): add ghost linked document to home

shared/elasticsearch-document-adapter/src/ingest.js, shared/elasticsearch/src/vectorizer/index.js
=> refactor(vector): add concurrency and log

shared/elasticsearch-document-adapter/src/ingest.js
=> fix: wrong logger level

README-dev.md
Documentation à jour. N'hésitez pas à la mettre à jour s'il manque des points durant votre test.
=> docs: add a section to describe how to populate elasticsearch database

targets/alert-cli/README.md, targets/alert-cli/src/node-git.helpers.ts
=> fix(alerting): Handle new file in diff on Kali data. Co-author @m-maillot

shared/elasticsearch-document-adapter/src/cdtnDocuments.js
related to https://github.com/SocialGouv/code-du-travail-numerique/issues/4090
=> feat(ingester): add agreement highlight to contributions data

.k8s/__tests__/__snapshots__/generate-dev.ts.snap, .k8s/__tests__/__snapshots__/generate-preprod.ts.snap, .k8s/__tests__/__snapshots__/generate-prod.ts.snap, .k8s/__tests__/kosko generate/--env prod/jobs/restore/__snapshots__/index.ts.snap, .k8s/components/netpol.ts, .k8s/package.json, .k8s/yarn.lock
Add network isolation at kubernetes level
=> fix(secu): add k8s network policies and update snaps

targets/frontend/src/pages/ghost-documents.tsx
=> fix(frontend): references inaccessibles

targets/alert-cli/@types/unist-util-parents.d.ts, targets/alert-cli/src/diff/dila/Agreement/ProcessAgreementChanges.ts, targets/alert-cli/src/diff/dila/Agreement/ProcessAgreementFileChanges.ts, targets/alert-cli/src/diff/dila/Agreement/__tests__/dataset/filechanges_kali_agreement_added.json, targets/alert-cli/src/diff/dila/Agreement/__tests__/dataset/filechanges_kali_agreement_removed.json, targets/alert-cli/src/diff/dila/Agreement/__tests__/dilaDataDiff.spec.ts, targets/alert-cli/src/diff/dila/Agreement/__tests__/processAgreementFileChanges.spec.ts, targets/alert-cli/src/diff/dila/Agreement/types.ts, targets/alert-cli/src/diff/dila/Code/ProcessCodeChanges.ts, targets/alert-cli/src/diff/dila/Code/ProcessCodeFileChanges.ts, targets/alert-cli/src/diff/dila/Code/__tests__/dilaDataDiff.spec.ts, targets/alert-cli/src/diff/dila/CompareDilaContent.ts, targets/alert-cli/src/diff/dila/CompareTree.ts, targets/alert-cli/src/diff/dila/index.ts, targets/alert-cli/src/node-git.helpers.ts
Fix https://github.com/SocialGouv/cdtn-admin/issues/692
=> fix(compareTree): handle empty changes

targets/alert-cli/jest.config.js, targets/alert-cli/package.json
=> fix(alerting): __dirname is not defined

.k8s/__tests__/__snapshots__/generate-dev-sitemap-uploader.ts.snap, .k8s/__tests__/__snapshots__/generate-prod-sitemap-uploader.ts.snap, .k8s/environments/dev/sitemap-uploader/dev.configmap.yaml, .k8s/environments/prod/sitemap-uploader/preprod.configmap.yaml, .k8s/environments/prod/sitemap-uploader/prod.configmap.yaml, targets/frontend/src/__tests__/sitemap.test.js, targets/frontend/src/pages/api/sitemap.ts
Fix https://github.com/SocialGouv/code-du-travail-numerique/issues/4304
=> feat(sitemap): move sitemap from /api/sitemap to sitemap.xml to avoid redirection, make our editorial content with higher priority

targets/frontend/src/lib/azure.js
fix https://github.com/SocialGouv/code-du-travail-numerique/issues/4305
=> fix(upload): mimetype

targets/export-elasticsearch/.eslintrc.js, targets/export-elasticsearch/package.json, targets/export-elasticsearch/request.http, targets/export-elasticsearch/src/controllers/copy.ts, targets/export-elasticsearch/src/controllers/index.ts, targets/export-elasticsearch/src/controllers/sitemap.ts, targets/export-elasticsearch/src/repositories/azure.ts, targets/export-elasticsearch/src/repositories/index.ts, targets/export-elasticsearch/src/server.ts, targets/export-elasticsearch/src/services/copy.ts, targets/export-elasticsearch/src/services/index.ts, targets/export-elasticsearch/src/services/sitemap.ts, targets/export-elasticsearch/src/utils/buffer.ts, targets/export-elasticsearch/src/utils/index.ts, targets/frontend/src/hooks/exportEs.ts, targets/frontend/src/pages/api/export.ts, yarn.lock
=> feat(api): add sitemap upload

.github/workflows/sync-gitlab.yml
=> chore(gitlab): fix mirror path

shared/types/index.ts, targets/ingester/.eslintrc.yaml, targets/ingester/package.json, targets/ingester/src/cli.ts, targets/ingester/src/lib/fetchContributions/AgreementRepository.ts, targets/ingester/src/lib/fetchContributions/AnswerExtractor.ts, targets/ingester/src/lib/fetchContributions/ContributionRepository.ts, targets/ingester/src/lib/fetchContributions/index.ts, targets/ingester/src/lib/fetchContributions/query.ts, targets/ingester/src/lib/fetchContributions/types.ts, targets/ingester/src/transform/agreements/index.ts, targets/ingester/src/transform/contributions.ts, yarn.lock
Consume contributions data from the hasura database in place of the github repository.
=> feat(ingester): use the new contribution data

targets/frontend/src/pages/api/storage/index.js
=> fix(api): limit uploadable extensions

targets/contributions/next.config.js, targets/frontend/next.config.js
fix https://github.com/SocialGouv/cdtn-admin/issues/791
Via next.js
=> feat(headers): add security headers to frontend and contributions

targets/frontend/package.json, targets/frontend/src/lib/secu.ts, targets/frontend/src/pages/api/storage/index.js, targets/frontend/tsconfig.json, yarn.lock
=> fix(secu): sanitize upload to avoid xss attack

.kube-workflow/sql/post-restore.sql, docker-compose.yml, docker/elasticsearch/Dockerfile, docker/elasticsearch/elasticsearch.yml, targets/export-elasticsearch/README.md, targets/export-elasticsearch/package.json, targets/export-elasticsearch/src/services/export.ts, targets/export-elasticsearch/src/utils/name.ts
=> fix(ingester): ajout de feature qui permet de désactiver certaines parties du processus d'export

shared/elasticsearch-document-adapter/src/cdtnDocuments.ts, shared/elasticsearch/src/dataset/stop_words/stop_words.json, shared/elasticsearch/src/dataset/synonyms/cdtn_synonyms.json
https://github.com/SocialGouv/code-du-travail-numerique/issues/4442
https://github.com/SocialGouv/code-du-travail-numerique/issues/4441
=> fix(ccn): add default effectif / update ccn stopword and synos

.kontinuous/env/prod/values.yaml
adjust ressources to :
- www
- contributions
- export
add HPA to:
- www
- contributions
- export
=> update pod resources and set HPA

.kontinuous/env/prod/values.yaml, .kontinuous/values.yaml
Hello,
petit ajustement sur les resources en dev d'hasura. car actuellement la memoire requested par défaut est de `121Mi` alors que ca consomme ~500/600
=> chore(k8s): adjust hasura default resources

shared/dila-resolver/package.json, targets/alert-cli/package.json, yarn.lock
=> fix(dila-api-client): upgrade to latest version

shared/elasticsearch/src/dataset/synonyms/cdtn_synonyms.json, targets/export-elasticsearch/dataset/suggestions.txt, targets/frontend/src/lib/auth/token.js
fix https://github.com/SocialGouv/code-du-travail-numerique/issues/5213
=> feat(synonyms): ajout d'un synonyme pour la CC 1486

targets/frontend/src/components/contributions/answers/Answer.tsx
Bug : impossible de cliquer sur "remettre en rédaction"
=> présent sur chrome mais pas sur FF.
=> fix(contributions): make button behavior right on answer form

targets/hasura/metadata/databases/default/tables/auth_users.yaml
Salut,
Cette pull request a pour but de fermer cette [issue](https://github.com/SocialGouv/cdtn-admin/issues/955) (close #955)
=> fix(user): be able to create a super user

targets/frontend/package.json, targets/frontend/src/pages/api/activate_account.js, targets/frontend/src/pages/api/change_password.js, targets/frontend/src/pages/api/login.js, targets/frontend/src/pages/api/logout.js, targets/frontend/src/pages/api/refresh_token.js, targets/frontend/src/pages/api/reset_password.js, targets/frontend/src/pages/api/validation.js, targets/frontend/src/pages/api/webhooks/publication.js, yarn.lock
On préfèrera utiliser Zod à Joi qui gère mieux le typescript. Celui ci étant déjà utiliser sur le projet du frontend.
=> feat: migration de Joi vers Zod

shared/types/index.ts, targets/ingester/src/articles/kali/load-agreements.ts, targets/ingester/src/lib/fetchContributions/AgreementRepository.ts, targets/ingester/src/lib/fetchContributions/AnswerExtractor.ts, targets/ingester/src/lib/fetchContributions/__mocks__/AgreementMock.ts, targets/ingester/src/transform/agreements/index.ts, targets/ingester/src/transform/contributions.ts, targets/ingester/src/transform/fichesServicePublic/index.ts
refer to https://github.com/SocialGouv/code-du-travail-numerique/issues/5315
=> fix: add filtered for cc which doesnt have id in `kali-data`

targets/frontend/src/components/contributions/answers/references/KaliReferenceInput.tsx, targets/frontend/src/components/contributions/answers/references/kaliReferencesSearch.query.ts, targets/frontend/src/components/forms/Autocomplete/index.tsx, targets/frontend/src/lib/references/fetchKaliReferences.ts
PR pour les retours pour les refs de l'admin contribution
=> fix: contribution ref link

targets/frontend/src/components/contributions/answers/AnswerForm.tsx
Fix pour le bug de la validation sur les status qui empêche une edition
=> fix: bug contribution validation sur page non editable

targets/frontend/src/components/contributions/answers/Comment.tsx, targets/frontend/src/components/contributions/answers/Comments.tsx, targets/frontend/src/components/contributions/answers/comments.mutation.ts, targets/hasura/metadata/databases/default/tables/contribution_answer_comments.yaml, targets/hasura/metadata/databases/default/tables/public_kali_articles.yaml
=> feat(admin): ajout de la suppression d'un commentaire

shared/elasticsearch-document-adapter/src/cdtnDocuments.ts
Closes https://github.com/SocialGouv/code-du-travail-numerique/issues/5327
=> fix: inject highlights on contributions

targets/frontend/src/components/contributions/questions/EditQuestionForm.tsx, targets/frontend/src/components/contributions/questions/Question.query.ts, targets/frontend/src/components/contributions/type.ts, targets/hasura/metadata/databases/default/tables/contribution_question_messages.yaml, targets/hasura/migrations/default/1700139430720_update_contribution_question_messages_data/up.sql, targets/hasura/migrations/default/1700215552179_alter_table_contribution_question_messages_alter_column_content_agreement_unhandled/down.sql, targets/hasura/migrations/default/1700215552179_alter_table_contribution_question_messages_alter_column_content_agreement_unhandled/up.sql
ANSWER=question_messages.content_agreement
NOTHING/CDT/UNFAVOURABLE=question_messages.content_legal
UNKNOWN=question_messages.content_not_handled
=> feat: ajout des textes pour message blocs

README-dev.md, docker-compose.yml
Reverts SocialGouv/cdtn-admin#1164
=> Revert "fix(documentation): changement au niveau du déploiement des branches frontend /  backend"

.env, README-dev.md, docker-compose.yml, targets/frontend/package.json, targets/frontend/src/hoc/CustomUrqlClient.js, targets/frontend/src/lib/auth/token.js, targets/frontend/src/lib/emails/activateAccount.ts, targets/frontend/src/lib/emails/lostPassword.js
Utilisation du port 3001 sur l'admin pour éviter les conflits avec le frontend
=> feat(frontend): utilisation du port 3001

shared/types/index.ts, targets/export-elasticsearch/src/controllers/export.ts, targets/export-elasticsearch/src/repositories/graphql/mutation.ts, targets/export-elasticsearch/src/repositories/graphql/queries.ts, targets/export-elasticsearch/src/repositories/status.ts, targets/export-elasticsearch/src/services/__test__/fake/export.ts, targets/export-elasticsearch/src/services/export.ts, targets/export-elasticsearch/src/workers/ingester-preprod.ts, targets/frontend/src/components/export-es/Status.tsx, targets/frontend/src/hooks/exportEs.ts, targets/frontend/src/modules/export/components/document-list.tsx, targets/frontend/src/modules/export/components/export.tsx, targets/frontend/src/pages/api/export.ts, targets/hasura/migrations/default/1702537735282_alter_table_public_export_es_status_add_column_error/down.sql, targets/hasura/migrations/default/1702537735282_alter_table_public_export_es_status_add_column_error/up.sql
=> fix(export): ajout des messages d'erreur au niveau de l'UI de l'export

shared/elasticsearch-document-adapter/src/contributions/__tests__/generateLinkedContent.test.ts, shared/elasticsearch-document-adapter/src/contributions/fetchLinkedContent.ts, shared/elasticsearch-document-adapter/src/contributions/generate.ts, shared/elasticsearch-document-adapter/src/contributions/generateLinkedContent.ts, targets/frontend/src/modules/documents/api/documents.service.ts, targets/frontend/src/modules/export/components/export.tsx
Fix https://github.com/SocialGouv/cdtn-admin/issues/1187
=> feat: possibilité de publier des contributions même s'il y a des références vers des documents inexistants

targets/frontend/src/pages/contenus/create/[[...source]].tsx
=> fix(informations): desactivation de l'UI de création de page information sur `Contenu`

.gitignore, scripts/connect_db.sh, scripts/dump_db.sh
Ajout d'un script pour dump une BDD (et affiche la commande pour faire le restore ensuite :) )
Et ajout du support de DBeaver pour se connecter à la BDD :)
=> feat(scripts): support de DBeaver et ajout d'un script pour dump une BDD

targets/frontend/src/modules/contribution/mapContributionToDocument.ts
=> fix(contributions): ajout des contributions pour les contributions sans CDT

shared/utils/src/url-generator.ts, targets/ingester/src/transform/fichesServicePublic/format.ts
C'est dommage mais nos URLs sont construites depuis l'ingester... je pense qu'il faudrait les déplacer pour les construire à l'export voir depuis le front. A voir. En tout cas ça corrige les redirect en canonical.
J'ai validé nos fiches pros et elles sont bien dispo sur `https://entreprendre.service-public.fr/`
```
https://entreprendre.service-public.fr/vosdroits/F19087 => 200
https://entreprendre.service-public.fr/vosdroits/F33665 => 200
https://entreprendre.service-public.fr/vosdroits/F31532 => 200
https://entreprendre.service-public.fr/vosdroits/F35360 => 200
https://entreprendre.service-public.fr/vosdroits/F24648 => 200
https://entreprendre.service-public.fr/vosdroits/F22542 => 200
https://entreprendre.service-public.fr/vosdroits/F17485 => 200 …
```
=> fix(fiche-sp): nouveau format de l'url pour les fiches pros

targets/export-elasticsearch/src/ingester/glossary/createGlossaryTransform.ts, targets/frontend/src/components/glossary/TermForm.js
Fix [Le glossaire ne gère pas le markdown](https://github.com/SocialGouv/cdtn-admin/issues/1024)
=> feat(glossaire): retrait du markdown dans les définitions du glossaire

targets/frontend/src/components/forms/EditionField/extensions/Titles.ts
closes [#1285](https://github.com/SocialGouv/cdtn-admin/issues/1285)
=> fix(contribution): rendu des headings

targets/export-elasticsearch/src/ingester/documents/fetchGlossary.ts, targets/export-elasticsearch/src/ingester/glossary/__mock__/glossaryData.ts, targets/export-elasticsearch/src/ingester/types.ts
co-author @carolineBda 
linked to https://github.com/SocialGouv/cdtn-admin/pull/1281
=> fix(glossary): rajout du `slug` et des `references` pour le glossaire

shared/utils/src/array-utils.ts, targets/frontend/src/modules/export/components/document-list.tsx, targets/frontend/src/modules/export/document.query.ts, targets/hasura/metadata/databases/default/tables/public_documents.yaml
=> fix(export): affichage du nombre de documents mis à jour

targets/hasura/migrations/default/1708090757744_alter_table_public_documents_add_check_constraint_slug_not_null_and_not_empty/down.sql, targets/hasura/migrations/default/1708090757744_alter_table_public_documents_add_check_constraint_slug_not_null_and_not_empty/up.sql, targets/hasura/migrations/default/1708090794355_alter_table_public_documents_add_check_constraint_source_not_null_and_not_empty/down.sql, targets/hasura/migrations/default/1708090794355_alter_table_public_documents_add_check_constraint_source_not_null_and_not_empty/up.sql, targets/ingester/src/cli.ts, targets/ingester/src/lib/hasura-mutations-queries.ts
=> feat(ingester): garder la même url des fiches-sp et fiches-mt si le titre change

targets/frontend/src/modules/agreements/components/Common/Form.tsx, targets/frontend/src/modules/agreements/components/Edition/delete.mutation.ts, targets/frontend/src/modules/agreements/components/Edition/index.tsx, targets/hasura/metadata/databases/default/tables/agreement_agreements.yaml
=> feat(agreement): supprimer une convention collective

targets/export-elasticsearch/src/ingester/contributions/__tests__/generateContent.test.ts, targets/export-elasticsearch/src/ingester/contributions/generateContent.ts
Petite amélioration mais très utile pour retrouver la source du problème :)
=> fix(export): améliorer un message d'erreur lors de l'export des contributions

targets/hasura/migrations/default/1709629363000_add_lot_4/down.sql, targets/hasura/migrations/default/1709629363000_add_lot_4/up.sql
closes [#5644](https://github.com/SocialGouv/code-du-travail-numerique/issues/5644)
=> feat(contribution): livraison du lot 4

targets/export-elasticsearch/src/ingester/exportStatus/updateExportEsStatusWithDocumentsCount.ts, targets/export-elasticsearch/src/ingester/glossary/__tests__/glossary.test.ts, targets/export-elasticsearch/src/ingester/glossary/explodeGlossaryTerms.ts
closes [#1339](https://github.com/SocialGouv/cdtn-admin/issues/1339)
=> fix(glossary): gère le cas de multiple strong dans un summary

targets/export-elasticsearch/src/ingester/cdtnDocuments.ts, targets/export-elasticsearch/src/ingester/prequalified/__tests__/generatePrequalified.test.ts, targets/export-elasticsearch/src/ingester/prequalified/fetchPrequalified.ts, targets/export-elasticsearch/src/ingester/prequalified/generatePrequalified.ts, targets/export-elasticsearch/src/ingester/utils/__tests__/removeUndefinedKeys.test.ts, targets/export-elasticsearch/src/ingester/utils/removeUndefinedKeys.ts
fix https://github.com/SocialGouv/code-du-travail-numerique/issues/5743
fix #1353
=> fix(export): ajout des éléments liés aux outils sur les préqualifiés

targets/frontend/src/pages/api/sitemap.ts, targets/hasura/migrations/default/1714661337149_run_sql_migration/down.sql, targets/hasura/migrations/default/1714661337149_run_sql_migration/up.sql
fix https://github.com/SocialGouv/code-du-travail-numerique/issues/5834
=> fix(tools): ignore in sitemap tools which are `displayTool: false`

.github/workflows/codeql-analysis.yml
fix [#1385](https://github.com/SocialGouv/cdtn-admin/issues/1385)
=> fix(actions): upgrade codeql to latest version

targets/frontend/src/modules/contribution/__tests__/mapContributionToDocument.test.ts, targets/frontend/src/modules/contribution/mapContributionToDocument.ts
fix [#5877](https://github.com/SocialGouv/code-du-travail-numerique/issues/5877)
=> fix(contributions): écrasement de contribution par d'autres contributions à la publication

targets/hasura/migrations/default/1708427376180_create_table_contribution_agreement_messages/up.sql, targets/hasura/migrations/default/1715084981000_insert_contribution_agreement_messages/down.sql, targets/hasura/migrations/default/1715084981000_insert_contribution_agreement_messages/up.sql
Fix [#1375](https://github.com/SocialGouv/cdtn-admin/issues/1375)
=> fix(contributions): ajout d'un message texte applicable pour les contributions de la 3239

targets/alert-cli/src/dares/__mocks__/page_dares.html, targets/alert-cli/src/dares/__tests__/scrapping.test.ts
Un petit test unitaire en plus pour tester le contenu 
fix #1421
=> fix(alert-cli): dares xlsx are unaccessible

docker-compose.yml, shared/types/src/utility.ts, shared/utils/src/__tests__/url-generator.test.ts, shared/utils/src/url-generator.ts, targets/frontend/src/components/changes/ChangeGroup.tsx, targets/ingester/src/transform/fichesServicePublic/format.ts
Fix [#1417](https://github.com/SocialGouv/cdtn-admin/issues/1417)
=> fix(alerting): urls correctes des fiches SP dans les alerts

targets/export-elasticsearch/src/ingester/prequalified/__tests__/generatePrequalified.test.ts, targets/export-elasticsearch/src/ingester/prequalified/fetchPrequalified.ts, targets/export-elasticsearch/src/ingester/prequalified/generatePrequalified.ts, targets/hasura/migrations/default/1720015045553_update_agreement_7026_slug/down.sql, targets/hasura/migrations/default/1720015045553_update_agreement_7026_slug/up.sql
linked to https://github.com/SocialGouv/code-du-travail-numerique/issues/5964
=> fix(agreements): mise à jour du slug de la convention collective 7026

targets/export-elasticsearch/.eslintrc.js, targets/export-elasticsearch/.eslintrc.json, targets/export-elasticsearch/request.http, targets/export-elasticsearch/src/controllers/__test__/export.test.ts, targets/export-elasticsearch/src/controllers/__test__/fake/export.ts, targets/export-elasticsearch/src/controllers/export.ts, targets/export-elasticsearch/src/ingester/types/GraphQL.ts, targets/export-elasticsearch/src/services/__test__/export.test.ts, targets/export-elasticsearch/src/services/__test__/fake/agreements.ts, targets/export-elasticsearch/src/services/export.ts, targets/frontend/src/modules/export/components/export.tsx, targets/frontend/src/modules/export/hooks/export.ts, targets/frontend/src/pages/api/export.ts
=> fix(export): correction de l'erreur d'affichage

targets/export-elasticsearch/src/ingester/documents/updateExportStatuses.ts, targets/frontend/src/components/contributions/answers/Answer.tsx, targets/frontend/src/components/contributions/answers/__tests__/AnswerForm.test.tsx, targets/frontend/src/components/contributions/answers/answer.query.ts, targets/frontend/src/components/contributions/questions/EditQuestionAnswerList.tsx, targets/frontend/src/components/contributions/questions/Question.query.ts, targets/frontend/src/components/contributions/type.ts, targets/hasura/metadata/databases/default/tables/contribution_answers.yaml, targets/hasura/metadata/databases/default/tables/public_document_exports.yaml, targets/hasura/metadata/databases/default/tables/public_documents.yaml, targets/hasura/migrations/default/1723540973286_delete_fk_contribution_answers_answers_cdtn_id_fkey/down.sql, targets/hasura/migrations/default/1723540973286_delete_fk_contribution_answers_answers_cdtn_id_fkey/up.sql, targets/hasura/migrations/default/1723541035763_set_fk_contribution_answers_cdtn_id/down.sql, targets/hasura/migrations/default/1723541035763_set_fk_contribution_answers_cdtn_id/up.sql, targets/hasura/migrations/default/1723541094652_alter_table_public_document_exports_add_unique_cdtn_id_export_id/down.sql, targets/hasura/migrations/default/1723541094652_alter_table_public_document_exports_add_unique_cdtn_id_export_id/up.sql, targets/hasura/migrations/default/1723541112319_set_fk_public_document_exports_cdtn_id/down.sql, targets/hasura/migrations/default/1723541112319_set_fk_public_document_exports_cdtn_id/up.sql, targets/hasura/migrations/default/1723541129468_set_fk_public_document_exports_export_id/down.sql, targets/hasura/migrations/default/1723541129468_set_fk_public_document_exports_export_id/up.sql, targets/hasura/migrations/default/1723559375436_alter_table_public_document_exports_add_column_created_at/down.sql, targets/hasura/migrations/default/1723559375436_alter_table_public_document_exports_add_column_created_at/up.sql, targets/hasura/migrations/default/1723559383013_alter_table_public_document_exports_add_column_updated_at/down.sql, targets/hasura/migrations/default/1723559383013_alter_table_public_document_exports_add_column_updated_at/up.sql
J'ai également ajouté les delete et update avec des `cascades` au lieu des `restrict`
=> fix(export-es): changement de la key unique `cdtn_id` par une key `cdtn_id` + `export_id`

targets/frontend/src/modules/agreements/__tests__/mapAgreementToDocument.test.ts, targets/frontend/src/modules/agreements/mapAgreementToDocument.ts, targets/hasura/migrations/default/1727965175418_update_cc_clug/up.sql
Fix [#1485](https://github.com/SocialGouv/cdtn-admin/issues/1485)
=> fix(convention collectives): fix de la generation du slug pour les CC qui sont créés

.kontinuous/env/prod/values.yaml
=> fix(performance): set better perf for `cnpg-cluster`

.github/workflows/quality.yml, targets/export-elasticsearch/src/ingester/cdtnDocuments.ts, targets/frontend/next-env.d.ts, targets/frontend/package.json, targets/frontend/src/modules/informations/components/informationsEdit/editInformation.mapping.ts, yarn.lock
=> fix(pages-infos): problème de sauvegarde des contenus `Dossier licenciement` 

targets/ingester/src/articles/kali/update-agreement-articles.ts
Fix pour l'erreur du cron ingester sur kali-data
=> fix: articles en doublons dans la CC 0843

shared/types/src/utility.ts
Correctif pour la PR : https://github.com/SocialGouv/code-du-travail-numerique/pull/6576
=> fix: support des tableaux dans le type KeysToCamelCase

targets/frontend/src/__tests__/sitemap.test.ts, targets/frontend/src/modules/sitemap/__tests__/date.spec.ts, targets/frontend/src/modules/sitemap/date.ts
fix https://github.com/SocialGouv/code-du-travail-numerique/issues/6563
=> fix(sitemap): passage au format ISO de la date
